# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 11:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_hour', models.BooleanField(default=False, verbose_name='Rapport horaire')),
                ('report_week', models.BooleanField(default=False, verbose_name='Rapport hebdomadaire')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnements mail',
            },
        ),
    ]
