# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 12:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('abbrv', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Abbréviation')),
                ('name', models.CharField(max_length=75, verbose_name='Intitulé complet')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté le')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Type de contrat',
                'verbose_name_plural': 'Types de contrats',
                'ordering': ['abbrv'],
            },
        ),
        migrations.CreateModel(
            name='GeorezoHisto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_forum', models.IntegerField(blank=True, null=True)),
                ('id_rss', models.IntegerField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('contrat', models.TextField(blank=True, null=True)),
                ('visites', models.IntegerField(blank=True, null=True)),
                ('dpt1', models.TextField(blank=True, null=True)),
                ('dpt2', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('region_typ', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Ajoutée le')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
            ],
            options={
                'verbose_name': 'Historique des offres de GeoRezo',
                'db_table': 'georezo_histo',
                'get_latest_by': 'pub_date',
            },
        ),
        migrations.CreateModel(
            name='GeorezoRSS',
            fields=[
                ('id_rss', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('source', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté le')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name_plural': "Offres d'emploi brutes issues du RSS de GeoRezo",
                'db_table': 'georezo_rss',
                'get_latest_by': 'pub_date',
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Intitulé')),
                ('comment', models.CharField(blank=True, max_length=5, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Métier',
                'verbose_name_plural': 'Métiers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobPositionVariations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='UNDEFINED', max_length=200, verbose_name='Variante du libellé')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.JobPosition', verbose_name='Métier correspondant')),
            ],
            options={
                'verbose_name': 'Variante de métier',
                'verbose_name_plural': 'Variantes des métiers',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rss', models.IntegerField(blank=True, db_index=True, unique=True)),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('pub_date', models.DateTimeField(verbose_name='Date de publication sur le RSS')),
                ('week', models.IntegerField(help_text='Format : <em>YYYYSS</em>.', verbose_name='Semaine de publication')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Ajoutée le')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Contract', verbose_name='Type de contrat')),
                ('jobs_positions', models.ManyToManyField(to='jobs.JobPosition', verbose_name='Métiers')),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['id_rss'],
                'get_latest_by': 'pub_date',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Nom')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Code')),
                ('scale', models.CharField(blank=True, choices=[('DEPARTEMENT', 'Département français'), ('COUNTRY', 'Pays étranger'), ('UNDEFINED', 'Indéfini')], db_index=True, default='DEPARTEMENT', max_length=50, verbose_name='Echelle')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté le')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Lieu',
                'verbose_name_plural': 'Lieux',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PlaceVariations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='UNDEFINED', max_length=200, verbose_name='Variante du libellé')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Place', verbose_name='Lieu correspondant')),
            ],
            options={
                'verbose_name': 'Variante de lieu',
                'verbose_name_plural': 'Variantes des lieux',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='GEOREZO_RSS', max_length=50, unique=True, verbose_name='Nom')),
                ('url', models.URLField(blank=True, verbose_name='Adresse web')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Ajoutée le')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
            ],
            options={
                'verbose_name': "Source de l'offre",
                'verbose_name_plural': 'Sources',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='ND', max_length=50, unique=True)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': "Statut de l'offre",
                'verbose_name_plural': 'Statuts de publication',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Nom')),
                ('license', models.CharField(choices=[('OSS', 'Libre'), ('PROPRIETARY', 'Propriétaire'), ('UNDEFINED', 'Indéfini')], default='UNDEFINED', max_length=20, verbose_name='Licence principale')),
                ('type_soft', models.CharField(choices=[('LANGUAGE', 'Language de programmation'), ('PROPRIETARY', 'Logiciel'), ('UNDEFINED', 'Indéfini')], default='UNDEFINED', max_length=50, verbose_name='Catégorie')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Ajoutée le')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
            ],
            options={
                'verbose_name': 'Technologie',
                'verbose_name_plural': 'Technologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TechnologyVariations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='UNDEFINED', max_length=200, verbose_name='Variante du libellé')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Technology', verbose_name='Technologie correspondante')),
            ],
            options={
                'verbose_name': 'Variante des technologies',
                'verbose_name_plural': 'Variantes des technologies',
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Place', verbose_name='Lieu'),
        ),
        migrations.AddField(
            model_name='offer',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Source', verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Status', verbose_name='Statut de publication'),
        ),
        migrations.AddField(
            model_name='offer',
            name='technologies',
            field=models.ManyToManyField(to='jobs.Technology', verbose_name='Technologies'),
        ),
        migrations.AlterUniqueTogether(
            name='georezorss',
            unique_together=set([('id_rss', 'pub_date', 'source')]),
        ),
    ]
