# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 17:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='georezohisto',
            options={'get_latest_by': 'pub_date', 'verbose_name': 'Historique des offres de GeoRezo', 'verbose_name_plural': 'Historique des offres de GeoRezo'},
        ),
        migrations.AlterField(
            model_name='georezohisto',
            name='contrat',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='georezohisto',
            name='dpt1',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='georezohisto',
            name='dpt2',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='georezohisto',
            name='id_forum',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='georezohisto',
            name='id_rss',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='georezohisto',
            name='pub_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='georezohisto',
            name='region',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='georezohisto',
            name='region_typ',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='georezohisto',
            name='summary',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='georezohisto',
            name='title',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='georezohisto',
            name='visites',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='georezorss',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
    ]
