# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 17:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20180124_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='georezorss',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.MaxLengthValidator(250)]),
        ),
    ]
