# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20180124_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='georezorss',
            name='to_update',
            field=models.BooleanField(db_index=True, default=0, help_text="Cocher cette case pour que l'offre soit de nouveau analysée à la prochaine mise à jour.", verbose_name='Analyser de nouveau'),
        ),
    ]
