# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20180128_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='type_soft',
            field=models.CharField(choices=[('LANGUAGE', 'Language de programmation'), ('SOFTWARE', 'Logiciel'), ('UNDEFINED', 'Indéfini')], default='UNDEFINED', max_length=50, verbose_name='Catégorie'),
        ),
    ]
