# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 11:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20180129_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='georezorss',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name="Contenu de l'offre"),
        ),
        migrations.AlterField(
            model_name='georezorss',
            name='id_rss',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='Identifiant du flux RSS'),
        ),
        migrations.AlterField(
            model_name='georezorss',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.MaxLengthValidator(250)], verbose_name="Titre de l'offre"),
        ),
    ]
