# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20180201_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='scale',
            field=models.CharField(blank=True, choices=[('DEPARTEMENT', 'Département français'), ('TOM', 'Territoire français'), ('COUNTRY', 'Pays étranger'), ('UNDEFINED', 'Indéfini')], db_index=True, default='DEPARTEMENT', max_length=50, verbose_name='Echelle'),
        ),
    ]
