# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 15:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20180219_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='raw_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_offer_uuid', to='jobs.GeorezoRSS'),
        ),
        migrations.AlterField(
            model_name='georezorss',
            name='title',
            field=models.CharField(blank=True, help_text='Doit être de la forme [TYPE_CONTRAT] INTITULÉ - LIEU (CODE_DÉPARTEMENT_OU_PAYS)', max_length=250, null=True, validators=[django.core.validators.MaxLengthValidator(250)], verbose_name="Titre de l'offre"),
        ),
    ]
