# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20180417_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='raw_id',
        ),
        migrations.AddField(
            model_name='offer',
            name='raw_offer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_offer', to='jobs.GeorezoRSS'),
        ),
    ]
