# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-10 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20180417_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractVariations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='UNDEFINED', max_length=200, verbose_name='Variante du libellé')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Contract', verbose_name='Type de contrat correspondant')),
            ],
            options={
                'verbose_name': 'Variante du type de contrat',
                'verbose_name_plural': 'Variantes des types de contrats',
            },
        ),
    ]
