# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_contractvariations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='code',
            field=models.CharField(help_text="Code du département ou  <a href='https://fr.wikipedia.org/wiki/ISO_3166-1#Table_de_codage'>code ISO à 3 lettres pour un pays (voir sur Wikipédia)</a>.", max_length=5, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='place',
            name='scale',
            field=models.CharField(blank=True, choices=[('DEPARTEMENT', 'Département français'), ('TOM', 'Territoire français'), ('COUNTRY', 'Pays'), ('UNDEFINED', 'Indéfini')], db_index=True, default='DEPARTEMENT', max_length=50, verbose_name='Echelle'),
        ),
    ]
