# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20180618_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='raw_offer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clean_offer', to='jobs.GeorezoRSS'),
        ),
    ]
