# Generated by Django 2.0.6 on 2018-06-28 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20180627_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='status',
        ),
        migrations.AlterField(
            model_name='contractvariations',
            name='name',
            field=models.ForeignKey(default='UNDEFINED', on_delete=django.db.models.deletion.SET_DEFAULT, to='jobs.Contract', verbose_name='Type de contrat correspondant'),
        ),
        migrations.AlterField(
            model_name='jobpositionvariations',
            name='name',
            field=models.ForeignKey(default='UNDEFINED', on_delete=django.db.models.deletion.SET_DEFAULT, to='jobs.JobPosition', verbose_name='Métier correspondant'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='contract',
            field=models.ForeignKey(default='ND', on_delete=django.db.models.deletion.SET_DEFAULT, to='jobs.Contract', verbose_name='Type de contrat'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='place',
            field=models.ForeignKey(default='ND', on_delete=django.db.models.deletion.SET_DEFAULT, to='jobs.Place', verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='source',
            field=models.ForeignKey(default='GEOREZO_RSS', on_delete=django.db.models.deletion.SET_DEFAULT, to='jobs.Source', verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='placevariations',
            name='name',
            field=models.ForeignKey(default='UNDEFINED', on_delete=django.db.models.deletion.SET_DEFAULT, to='jobs.Place', verbose_name='Lieu correspondant'),
        ),
        migrations.AlterField(
            model_name='technologyvariations',
            name='name',
            field=models.ForeignKey(default='UNDEFINED', on_delete=django.db.models.deletion.SET_DEFAULT, to='jobs.Technology', verbose_name='Technologie correspondante'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
