# Generated by Django 2.0.6 on 2018-07-03 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20180628_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.Source', verbose_name='Source'),
        ),
    ]
