# Generated by Django 2.0.6 on 2018-07-03 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_auto_20180703_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='content',
            field=models.TextField(null=True, verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='contract',
            field=models.ForeignKey(default='ND', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='jobs.Contract', verbose_name='Type de contrat'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='place',
            field=models.ForeignKey(default='ND', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='jobs.Place', verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='Date de publication sur le RSS'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='week',
            field=models.IntegerField(help_text='Format : <em>YYYYSS</em>.', null=True, verbose_name='Semaine de publication'),
        ),
    ]
