version: 2
updates:

  - package-ecosystem: pip
    directory: ".deploy/apache/"
    schedule:
      interval: monthly
      time: "04:00"
      timezone: Europe/Paris
    reviewers:
      - Guts
    labels:
      - dependencies

  - package-ecosystem: pip
    directory: "requirements/"
    schedule:
      interval: monthly
      time: "04:00"
      timezone: Europe/Paris
    reviewers:
      - Guts
    labels:
      - dependencies
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - Guts
    labels:
      - ci-cd
      - dependencies
