# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "node_modules|migrations|.venv|tests/dev/|tests/fixtures/"
fail_fast: true
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: trailing-whitespace
    # files: (^|/)a/.+\.(py|html|sh|css|js)$
  - id: check-yaml
  - id: detect-private-key
  - id: fix-encoding-pragma
- repo: https://github.com/python/black
  rev: 19.10b0
  hooks:
  - id: black
    exclude_types: [directory,]
    language_version: python3
    log_file: ./dev_precommit.log
    require_serial: true
    types: [file, python]
