language: python

env:
  - ELPASO_DEBUG_SETTING=1

python:
  - "3.5"

# database
services:
  - postgresql

# caching to improve next builds
cache: pip

# see: https://docs.travis-ci.com/user/database-setup/#postgresql-and-locales
before_install:
  - sudo apt-get update
  - sudo apt-get install language-pack-fr

# specify postgresql version and add postgis
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

# dependencies
install:
  - "pip install --upgrade setuptools wheel"
  - "pip install --upgrade -r requirements.txt"


# prepare database
before_script:
  - psql -c "CREATE DATABASE elpaso;" -U postgres
  - psql -c "CREATE USER geotribu WITH PASSWORD 'TRAVISTESTDB';" -U postgres
  - psql -c "ALTER ROLE geotribu SET client_encoding TO 'utf8';" -U postgres
  - psql -c "ALTER DATABASE elpaso SET timezone TO 'Europe/Paris';" -U postgres
  - psql -c "ALTER ROLE geotribu SET default_transaction_isolation TO 'read committed';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE elpaso TO geotribu;" -U postgres
  - psql -d elpaso -c "CREATE EXTENSION postgis;" -U postgres
  - psql -d elpaso -c "CREATE EXTENSION postgis_topology;" -U postgres

# run tests
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py collectstatic --noinput
