# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 13:17
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_cms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Corps de texte'),
        ),
    ]
