# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 13:17
from __future__ import unicode_literals

from django.db import migrations
from django_ckeditor_5.fields import CKEditor5Field


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_cms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=CKEditor5Field(verbose_name='Corps de texte'),
        ),
    ]
