# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 13:27
from __future__ import unicode_literals

from django.db import migrations, models
from django_ckeditor_5.fields import CKEditor5Field


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20180308_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Publié'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=CKEditor5Field(verbose_name='Corps de texte'),
        ),
    ]
