# Generated by Django 2.2.12 on 2020-05-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20180628_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
