# Generated by Django 4.2.25 on 2025-10-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0004_auto_20180628_2357"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
