# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 09:46
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('cms', '0001_initial'), ('cms', '0002_auto_20180115_1329'), ('cms', '0003_auto_20180115_1415'), ('cms', '0004_auto_20180117_0846'), ('cms', '0005_article_ext_url')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Titre')),
                ('content', ckeditor.fields.RichTextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur.e')),
            ],
            options={
                'verbose_name': 'Contenu éditorial',
                'verbose_name_plural': 'Contenus éditoriaux',
                'ordering': ['title'],
                'get_latest_by': 'updated',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('slug_name', models.SlugField(blank=True, unique=True, verbose_name='Alias normé')),
            ],
            options={
                'verbose_name': 'Type de contenu',
                'verbose_name_plural': 'Types de contenu',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Category', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='article',
            name='slug_title',
            field=models.SlugField(blank=True, unique=True, verbose_name='Alias normé'),
        ),
        migrations.AddField(
            model_name='article',
            name='ext_url',
            field=models.URLField(blank=True, verbose_name='Lien externe'),
        ),
    ]
