# Generated by Django 2.2.12 on 2020-04-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_offer_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractvariations',
            name='label',
            field=models.CharField(max_length=200, unique=True, verbose_name='Variante du libellé'),
        ),
        migrations.AlterField(
            model_name='jobpositionvariations',
            name='label',
            field=models.CharField(default='UNDEFINED', max_length=200, unique=True, verbose_name='Variante du libellé'),
        ),
        migrations.AlterField(
            model_name='placevariations',
            name='label',
            field=models.CharField(default='UNDEFINED', max_length=200, unique=True, verbose_name='Variante du libellé'),
        ),
        migrations.AlterField(
            model_name='technologyvariations',
            name='label',
            field=models.CharField(default='UNDEFINED', max_length=200, unique=True, verbose_name='Variante du libellé'),
        ),
    ]
